# task 
tokenlabeling: False

# Dataset parameters
train_split: 'Train'
val_split: 'Val'

# Model parameters
initial_checkpoint: ''
resume: ''
num_classes: 3
chans: 1
img_size: 224
input_size: [1, 224, 224] # replace the chans and img_size
crop_pct: 0.875




