# task 
tokenlabeling: False

# data path
data_dir: '/mnt/d/Data/COVID_QU/Infection Segmentation Data/Infection Segmentation Data'
# Dataset parameters
train_split: 'Train'
val_split: 'Val'

# Model parameters
initial_checkpoint: ''
resume: ''
greyscale: True
num_classes: 3
chans: 1
img_size: 224
input_size: [1, 224, 224] # replace the chans and img_size
crop_pct: 0.875
gp:
mean: [0.5128]
std: [0.2236]




